name: Add to Infrastructure as Code (IaC) project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add To GitHub Projects
    runs-on: ubuntu-latest

    steps:
      # Add To GitHub Projects Beta
      # https://github.com/marketplace/actions/add-to-github-projects-beta
      - name: Add To GitHub IaC Project
        uses: actions/add-to-project@v0.0.3
        with:
          project-url: https://github.com/orgs/osinfra-io/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}